module.exports = {
  "ALIVE_IMG": "https://i.ibb.co/4wJnJV5z/8212.jpg",
  "PREFIX": ".",
  "AUTO_READ_STATUS": true,
  "MODE": "public",
  "BOT_NUMBER": "94771464482",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": true,
  "AUTO_VOICE": false,
  "AUTO_STICKER": false,
  "AUTO_REPLY": true,
  "AUTO_REACT": false,
  "WELCOME": true,
  "ANTI_BAD": false,
  "ANTI_BOT": true,
  "ANTI_LINK": false,
  "ANTI_CALL": false,
  "ANTI_DELETE": false,
  "ALLWAYS_ONLINE": true,
  "MOROCCO_BLOCK": true,
  "BTN_MSG": false,
  "OWNER_NAME": "MR DRK",
  "NEWS_JID": "1234567890@s.whatsapp.net",
  "MOVIE_JID": "120363367650594508@g.us",
  "ANIME_JID": "120363367650594508@g.us",
  "AUTO_TYPING": false,
  "AUTO_RECORDING": true,
  "AUTO_NEWS": false,
  "OWNER_REACT": false,
  "EMOJI": "🏷",
  "AI_MODE": false,
  "BANNED": [],
  "SUDO": [
    "94758775628"
  ]
};